spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=social
    username: postgres
    password: Khanhhoa123@
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org:
      hibernate: INFO
      springframework:
        ws: TRACE
